version: '3.8'
services:
  backend:
    build: ./BE
    env_file:
      - ./BE/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./FE
    env_file:
      - ./FE/.env
    ports:
      - "5173:5173"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 비밀번호입력
      MYSQL_DATABASE: 데이터베이스이름
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
