spring:
  application:
    name: BE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul   # ✅ UTC → Asia/Seoul
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul        # ✅ UTC → Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

    servlet:
      multipart:
        max-file-size: 15MB
        max-request-size: 15MB

gms:
  api:
    key: ${GMS_API_KEY}
    url: ${GMS_API_URL}
    model: gpt-4o
  image:
    api:
      url: ${GMS_IMAGE_API_URL}

cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: daon-image
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

frontend:
  origin: http://localhost:5173

tesseract:
  path: "/usr/share/tesseract-ocr/5/tessdata"

logging:
  level:
    root: INFO
    com.daon.be: DEBUG
    org.springframework.web: DEBUG
