default:
  tags: ["daon"]

stages:
  - build
  - deploy

# 1) Docker 이미지 빌드 & 푸시
build-and-push:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'   # deploy 브랜치에서만 실행
  script:
    - echo "=== Docker Hub Login ==="
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"

    - echo "=== Docker Build ==="
    - docker build -t "$IMAGE_NAME:latest" "$BACKEND_DIR"

    - echo "=== Docker Push ==="
    - docker push "$IMAGE_NAME:latest"

    - echo "=== Build & Push Finished ==="

# 2) EC2에서 컨테이너 교체
deploy-backend:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'
  script:
    - echo "=== Stop & Remove Existing Container ==="
    - docker stop "$CONTAINER_NAME" || true
    - docker rm "$CONTAINER_NAME" || true

    - echo "=== Pull Latest Image ==="
    - docker pull "$IMAGE_NAME:latest"

    - echo "=== Run New Container ==="
    - docker run -d --name "$CONTAINER_NAME" \
      --env-file "$ENV_FILE" \
      -p "$HOST_PORT:$CONTAINER_PORT" \
      "$IMAGE_NAME:latest"

    - echo "=== Deployment Finished ==="
